---
title: "NYCSpatial"
author: "Laura Hoyte"
date: "April 13, 2016"
output: html_document
---

```{r libraries, echo = FALSE}

library(rgdal)



```

## Load GeoJSON


```{r Load GeoJSON, echo = FALSE}

getmap <-  readOGR("C:/Mathlab/CV/Courses/DAND/P4 - Data Analysis with R/P4 Project/NYC Taxi/nyc.geojson", "OGRGeoJSON")

plot(getmap)

getcensus <- readOGR("C:/Mathlab/CV/Courses/DAND/P4 - Data Analysis with R/P4 Project/NYC Taxi/nyc_community_districts_2013.geojson", "OGRGeoJSON")
plot(getcensus)
rm(getmap)

getmap2 <- ogrInfo(dsn = "C:/Mathlab/CV/Courses/DAND/P4 - Data Analysis with R/P4 Project/NYC Taxi/nyc.geojson", layer = "OGRGeoJSON")

```

## Query MogoDB

```{r Query MongoDB, echo = FALSE}

getpoint <- c("pickup_longitude", "pickup_latitude")
coord <- taxiday[c("pickup_longitude", "pickup_latitude")]
long <- coord[1,1]
lat <- coord[1,2]

neighb <- mongo(collection = "neighb", db = "nyc", url = "mongodb://localhost", verbose = TRUE)
test <- neighb$find(
  paste0('{"geometry": 
                    {"$geoIntersects":
                                {"$geometry": {"type": "Point", 
                                            "coordinates": [', coord[1,1], ',', coord[1,2], ']}
                                }
                    }
          }'
        ), 
  fields = '{"_id":0, "properties.neighborhood":1, "properties.boroughCode":1, "properties.borough":1}')
  


aSample <- review.collection$aggregate(
paste0('[
{ "$project" : { "_id" : 0, "text" : 1 } },
{ "$sample" : { "size" : ', sampleSize, ' } }
]'))



```

## Query MongoDB Part2

```{r}

coord <- newtaxiday_loc[c("pickup_longitude", "pickup_latitude")]
long <- coord[1,1]
lat <- coord[1,2]
borough[c("neighborhood, boroughcode", "borough" )] <- NULL
borough <- as.data.frame(borough)

neighb <- mongo(collection = "neighb", db = "nyc", url = "mongodb://localhost", verbose = TRUE)

for (i in 1:dim(coord)[1]) {
  findborough <- neighb$find(
  paste0('{"geometry": 
                    {"$geoIntersects":
                                {"$geometry": {"type": "Point", 
                                            "coordinates": [', coord[i,1], ',', coord[i,2], ']}
                                }
                    }
          }'
        ), 
  fields = '{"_id":0, "properties.neighborhood":1, "properties.boroughCode":1, "properties.borough":1}')
  
  if(i == 1) {
    borough = findborough
  } else {
    #row.names(findborough) <- i
    borough <- bind_rows(borough, findborough)
  }
  
  print(i)
  
}

```

